image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - staging

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build_job:
  stage: build
  script:
  #- yarn -v
  #- yarn install
  #- cd ./websites/main
  #- chmod +x ./build.sh
  #- ./build.sh
  #- sh ./websites/landing/build.sh
  - ln -s ./websites/main/pages ./pages
  - ls -al
  - cd -P ./pages
  - ls -al


stage_deploy:
  only:
  - master
  stage: staging
  script:
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  - ssh -p2017 rs@145.239.85.163 "sh /var/www/update.sh"

