image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - staging

before_script:
  # - ....
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build_job:
  stage: build
  script:
  - node -v
  - npm install
  - npm run build

stage_deploy:
  stage: staging
  script:
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  - ssh -p2017 rs@besmarter.ru "sh /var/www/update.sh"

