image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build

build_job:
  stage: build
  script:
  - node -v
  - yarn install
  - yarn build

stage_deploy:
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 rs@bsmr.ru "touch hahaha"
    - ssh -p22 rs@bsmr.ru "touch ~/hahaha2"

  