
stages:
  - build

.trigger_project_master:
  stage: build
  script:
    - curl --request POST 
      --form "token=$CI_JOB_TOKEN" 
      --form ref=master 
      https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline
  only:
    - master

.trigger_project:
  stage: build
  script:
    - curl --request POST 
      --form "token=$CI_JOB_TOKEN" 
      --form ref=master 
      --form "variables[TRIGGER_COMMIT_SHA]=$CI_COMMIT_SHA"
      https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline
  except:
    - master

website-master:
  extends: .trigger_project_master
  variables:
    PROJECT_ID: 10934487

website:
  extends: .trigger_project
  variables:
    PROJECT_ID: 10934487

landing-student-bs-master:
  extends: .trigger_project_master
  variables:
    PROJECT_ID: 10934628

landing-student-bs:
  extends: .trigger_project
  variables:
    PROJECT_ID: 10934628

landing-student-consultant-master:
  extends: .trigger_project_master
  variables:
    PROJECT_ID: 10934643

landing-student-consultant:
  extends: .trigger_project
  variables:
    PROJECT_ID: 10934643
